version: '2'
services:
        backend:
                build: .
                command: yarn start
                volumes: 
                        - ./usr/app/
                        - /usr/app/node_modules
                ports:
                         - "3001:3001"
                         - "3002:3002"

