version: '2'
services:
        backend:
                build: .
                command: yarn start
                volumes: 
                        - /usr/app/
                        - /usr/app/node_modules
                ports:
                         - "3001:3001"
                         - "3002:3002"
                environment:
                        - SECRET_KEY=emdr3xp
                        - PORT=3002
                        - SYNC=TRUE
                        - DAILYCOAPIKEY=5cbedd991fbe5b230fd4bc9e72e85860d13235ee5cd254bb4b265621f1271efb
                        - WEBSOCKER_PORT=3001
                        - TWILIO_AUTH_TOKEN=bf593c3c33cc527656dcede84c05dc1f
                        - TWILIO_ACCOUNT_SID=AC03c5e8b254c18ee99cbab99044369ddf
                        - TWILIO_FROM_NUMBER=+14155238886
                        - MAILER_HOST=equipamentospsi.com
                        - MAILER_PORT=465
                        - MAILER_USER=contact@equipamentospsi.com
                        - MAILER_PASS=eu1Z%d06
                        - DATABASE_HOST=localhost
                        - DATABASE_PORT=3306
                        - DATABASE_USER=emdr
                        - DATABASE_PASSWORD=E5f5@9uq
                        - DATABASE_NAME=EDMR
                        - DATABASE_TYPE=mysql

