version: '2'
services:
        backend:
                build: .
                command: yarn start:production
                volumes:
                        - /usr/app/
                        - /usr/app/node_modules
                ports:
                        - "3001:3001"
                        - "3002:3002"
                environment:
                        - SECRET_KEY=emdr3xp
                        - PORT=3002
                        - SYNC=TRUE
                        - DAILYCOAPIKEY=1f154b8cfac0119377aab4d0b4ce3ea10d13e3a0e287a4441a2346a3190f9205
                        - WEBSOCKET_PORT=3001
                        - TWILIO_AUTH_TOKEN=bf593c3c33cc527656dcede84c05dc1f
                        - TWILIO_ACCOUNT_SID=AC03c5e8b254c18ee99cbab99044369ddf
                        - TWILIO_FROM_NUMBER=+14155238886
                        - MAILER_HOST=equipamentospsi.com
                        - MAILER_PORT=465
                        - MAILER_USER=contact@equipamentospsi.com
                        - MAILER_PASS=eu1Z%d06
                        - DATABASE_HOST=app.equipamentospsi.com
                        - DATABASE_PORT=3306
                        - DATABASE_USER=emdr-v2
                        - DATABASE_PASSWORD="y83l7Fh1#"
                        - DATABASE_NAME=emdr
                        - DATABASE_TYPE=mysql
